language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build || true
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
  steps:
